#cloud-config

users:
  - name: ${init_ssh_username}
    ssh_authorized_keys:
      - ${init_public_key}
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

ssh_pwauth: false

runcmd:
 - [ userdel, -r, ubuntu]
 - [ userdel, -r, linuxuser ]

package_update: false

package_upgrade: false