collections:
  - name: community.general
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
  - name: lablabs.wireguard
    source: https://galaxy.ansible.com
  - name: devsec.hardening
    source: https://galaxy.ansible.com
  - name: robertdebock.roles
    source: https://galaxy.ansible.com
