---

collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: 8.6.0
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 1.6.2
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: 8.7.0
  - name: robertdebock.roles
    source: https://galaxy.ansible.com
    version: 1.10.6

roles:
  - name: githubixx.ansible_role_wireguard
    version: 18.2.0
