collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: 8.6.0
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 1.5.4
  - name: lablabs.wireguard
    source: https://galaxy.ansible.com
    version: 0.3.3
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: 8.7.0
  - name: robertdebock.roles
    source: https://galaxy.ansible.com
    version: 1.10.6
